# Generated by Django 6.0 on 2025-12-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_tarea_fecha_completado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fecha_recordatorio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='recordatorio_activo',
            field=models.BooleanField(default=False),
        ),
    ]
