# Generated by Django 6.0 on 2025-12-18 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_tarea_fecha_recordatorio_tarea_recordatorio_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('color', models.CharField(choices=[('primary', 'Azul'), ('secondary', 'Gris'), ('success', 'Verde'), ('danger', 'Rojo'), ('warning', 'Amarillo'), ('info', 'Celeste'), ('dark', 'Negro')], default='primary', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='tarea',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tareas.categoria'),
        ),
    ]
