# Generated by Django 6.0 on 2025-12-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0006_categoria_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='recordatorio_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
