# Generated by Django 6.0 on 2025-12-26 20:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0011_perfil_tareas_completadas_total_alter_perfil_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='completada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tarea',
            name='dificultad',
            field=models.CharField(choices=[('facil', 'Fácil (+10 XP)'), ('media', 'Media (+20 XP)'), ('dificil', 'Difícil (+50 XP)')], default='facil', max_length=10),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
