# Generated by Django 6.0 on 2025-12-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0012_tarea_completada_tarea_dificultad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='destacada',
            field=models.BooleanField(default=False),
        ),
    ]
