# Generated by Django 6.0 on 2025-12-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0013_nota_destacada'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatares/'),
        ),
    ]
