"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os 
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-38j%+c@a#wj3kwufwd)dzj7=#0!esoqeq=f=08ja^12qy1wg%^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['nahuela.pythonanywhere.com', 'localhost', '127.0.0.1']

# ¡IMPORTANTE: Esta línea debe llevar 'https://' al principio!
CSRF_TRUSTED_ORIGINS = ['https://nahuela.pythonanywhere.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tareas',
    'django.contrib.humanize',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google', 
    'django.contrib.sites',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]


ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'tareas.context_processors.notificaciones_globales',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = []



# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True

USE_L10N = True

USE_THOUSAND_SEPARATOR = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# Redirigir aquí si el usuario no está logueado
LOGIN_URL = 'signin'


# ... al final del archivo ...

# CONFIGURACIÓN DE GMAIL (SMTP)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'nahuelaguilera68@gmail.com'  # <--- PON AQUÍ TU GMAIL REAL
EMAIL_HOST_PASSWORD = 'cwrr ydbf vppt bgqu'  # <--- PEGA AQUÍ LA CONTRASEÑA DE 16 LETRAS QUE TE DIO GOOGLE
DEFAULT_FROM_EMAIL = 'Gestor de Tareas <nahuelaguilera68@gmail.com>'
# --- CONFIGURACIÓN DE AUTH (Google) ---
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend', # Login normal
    'allauth.account.auth_backends.AuthenticationBackend', # Login con Google
]

SITE_ID = 1

# Redirección al entrar y salir
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'landing'  # O 'signin' si prefieres

# --- CONFIGURACIÓN DE LOGIN (LOGIN & ALLAUTH) ---

# 1. Redirección: A dónde ir después de entrar
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'signin'

# 2. Configuración de Allauth (¡Esto es lo que te falta!)
ACCOUNT_EMAIL_REQUIRED = True              # El email es obligatorio
ACCOUNT_USERNAME_REQUIRED = False          # El usuario no es obligatorio (usamos email)
ACCOUNT_AUTHENTICATION_METHOD = 'email'    # Entrar con email, no con usuario
ACCOUNT_EMAIL_VERIFICATION = 'none'        # ¡IMPORTANTE! No enviar email de confirmación (evita errores en local)
SOCIALACCOUNT_LOGIN_ON_GET = True          # Entrar directamente al hacer login con Google
SOCIALACCOUNT_AUTO_SIGNUP = True
# 3. Configuración específica de Google (Pide el email explícitamente)
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}
MEDIA_URL='/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# settings.py (al final)

# TEXTMEBOT CONFIG
WHATSAPP_PHONE = '+5493755264955'  # <--- IMPORTANTE: TextMeBot suele pedir el "+" adelante.
WHATSAPP_API_KEY = 'xTKkwgd94UGP'     # <--- La nueva clave que te den.